import productImageOne from "../assets/p6.png";
import productImageTwo from "../assets/p7.png";
import productImageThree from "../assets/p8.png";
import productImageFour from "../assets/p9.png";
import productImageFive from "../assets/p10.png";

let productInfo = [
  {
    badge: true,
    badgeText: "new",
    productImageSrc: productImageOne,
    productName: "Wireless Earbuds",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageTwo,
    productName: "Bluetooth HeadPhones",
    productPrice: "৳15.00",
    productColor: "green",
  },
  {
    badge: false,
    badgeText: "10%",
    productImageSrc: productImageThree,
    productName: "Water Bottles",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageFour,
    productName: "USB Cable",
    productPrice: "৳15.00",
    productColor: "white",
  },
  {
    badge: true,
    badgeText: "new",
    productImageSrc: productImageOne,
    productName: "Wireless Earbuds",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageTwo,
    productName: "Bluetooth Headphones",
    productPrice: "৳15.00",
    productColor: "blue",
  },
  {
    badge: false,
    badgeText: "10%",
    productImageSrc: productImageThree,
    productName: "Water Bottle",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageFour,
    productName: "USB Cable",
    productPrice: "৳15.00",
    productColor: "red",
  },
  {
    badge: true,
    badgeText: "new",
    productImageSrc: productImageOne,
    productName: "Wireless Earbuds",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageTwo,
    productName: "Bluetooth Headphones",
    productPrice: "৳15.00",
    productColor: "green",
  },
  {
    badge: false,
    badgeText: "10%",
    productImageSrc: productImageThree,
    productName: "Water Bottle",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageFour,
    productName: "USB Cable",
    productPrice: "৳15.00",
    productColor: "white",
  },
  {
    badge: true,
    badgeText: "new",
    productImageSrc: productImageOne,
    productName: "Wireless Earbuds",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageTwo,
    productName: "Bluetooth Headphones",
    productPrice: "৳15.00",
    productColor: "blue",
  },
  {
    badge: false,
    badgeText: "10%",
    productImageSrc: productImageThree,
    productName: "Water Bottle",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageFour,
    productName: "USB Cable",
    productPrice: "৳15.00",
    productColor: "red",
  },
  {
    badge: true,
    badgeText: "new",
    productImageSrc: productImageOne,
    productName: "Wireless Earbuds",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageTwo,
    productName: "Bluetooth Headphones",
    productPrice: "৳15.00",
    productColor: "green",
  },
  {
    badge: false,
    badgeText: "10%",
    productImageSrc: productImageThree,
    productName: "Water Bottle",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageFour,
    productName: "USB Cable",
    productPrice: "৳15.00",
    productColor: "white",
  },
  {
    badge: true,
    badgeText: "new",
    productImageSrc: productImageOne,
    productName: "Wireless Earbud",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageTwo,
    productName: "Bluetooth Headphones",
    productPrice: "৳15.00",
    productColor: "blue",
  },
  {
    badge: false,
    badgeText: "10%",
    productImageSrc: productImageThree,
    productName: "Water Bottle",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageFour,
    productName: "USB Cable",
    productPrice: "৳15.00",
    productColor: "red",
  },
  {
    badge: true,
    badgeText: "new",
    productImageSrc: productImageOne,
    productName: "Wireless Earbuds",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageTwo,
    productName: "Bluetooth Headphone",
    productPrice: "৳15.00",
    productColor: "green",
  },
  {
    badge: false,
    badgeText: "10%",
    productImageSrc: productImageThree,
    productName: "Water Bottle",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageFour,
    productName: "USB Cable",
    productPrice: "৳15.00",
    productColor: "white",
  },
  {
    badge: true,
    badgeText: "new",
    productImageSrc: productImageOne,
    productName: "Wireless Earbuds",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageTwo,
    productName: "Bluetooth Headphones",
    productPrice: "৳15.00",
    productColor: "blue",
  },
  {
    badge: false,
    badgeText: "10%",
    productImageSrc: productImageThree,
    productName: "Water Bottle",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageFour,
    productName: "USB Cable",
    productPrice: "৳15.00",
    productColor: "red",
  },
  {
    badge: true,
    badgeText: "new",
    productImageSrc: productImageOne,
    productName: "Wireless Earbuds",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageTwo,
    productName: "Bluetooth Headphones",
    productPrice: "৳15.00",
    productColor: "green",
  },
  {
    badge: false,
    badgeText: "10%",
    productImageSrc: productImageThree,
    productName: "Water Bottle",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageFour,
    productName: "USB Cable",
    productPrice: "৳15.00",
    productColor: "white",
  },
  {
    badge: true,
    badgeText: "new",
    productImageSrc: productImageOne,
    productName: "Wireless Earbuds",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageTwo,
    productName: "Bluetooth Headphones",
    productPrice: "৳15.00",
    productColor: "blue",
  },
  {
    badge: false,
    badgeText: "10%",
    productImageSrc: productImageThree,
    productName: "Water Bottle",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageFour,
    productName: "USB Cable",
    productPrice: "৳15.00",
    productColor: "red",
  },
  {
    badge: true,
    badgeText: "new",
    productImageSrc: productImageOne,
    productName: "Wireless Earbuds",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageTwo,
    productName: "Bluetooth Headphones",
    productPrice: "৳15.00",
    productColor: "green",
  },
  {
    badge: false,
    badgeText: "10%",
    productImageSrc: productImageThree,
    productName: "Water Bottle",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageFour,
    productName: "USB Cable",
    productPrice: "৳15.00",
    productColor: "white",
  },
  {
    badge: true,
    badgeText: "new",
    productImageSrc: productImageOne,
    productName: "Wireless Earbuds",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageTwo,
    productName: "Bluetooth Headphones",
    productPrice: "৳15.00",
    productColor: "blue",
  },
  {
    badge: false,
    badgeText: "10%",
    productImageSrc: productImageThree,
    productName: "Water Bottle",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageFour,
    productName: "USB Cable",
    productPrice: "৳15.00",
    productColor: "red",
  },
  {
    badge: true,
    badgeText: "new",
    productImageSrc: productImageOne,
    productName: "Wireless Earbuds",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageTwo,
    productName: "Bluetooth Headphones",
    productPrice: "৳15.00",
    productColor: "green",
  },
  {
    badge: false,
    badgeText: "10%",
    productImageSrc: productImageThree,
    productName: "Water Bottle",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageFour,
    productName: "USB Cable",
    productPrice: "৳15.00",
    productColor: "white",
  },
  {
    badge: true,
    badgeText: "new",
    productImageSrc: productImageOne,
    productName: "Wireless Earbuds",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageTwo,
    productName: "Bluetooth Headphones",
    productPrice: "৳15.00",
    productColor: "blue",
  },
  {
    badge: false,
    badgeText: "10%",
    productImageSrc: productImageThree,
    productName: "Water Bottle",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageFour,
    productName: "USB Cable",
    productPrice: "৳15.00",
    productColor: "red",
  },
  {
    badge: true,
    badgeText: "new",
    productImageSrc: productImageOne,
    productName: "Wireless Earbuds",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageTwo,
    productName: "Bluetooth Headphones",
    productPrice: "৳15.00",
    productColor: "green",
  },
  {
    badge: false,
    badgeText: "10%",
    productImageSrc: productImageThree,
    productName: "Water Bottle",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageFour,
    productName: "USB Cable",
    productPrice: "৳15.00",
    productColor: "white",
  },
  {
    badge: true,
    badgeText: "new",
    productImageSrc: productImageOne,
    productName: "Wireless Earbuds",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageTwo,
    productName: "Bluetooth Headphones",
    productPrice: "৳15.00",
    productColor: "blue",
  },
  {
    badge: false,
    badgeText: "10%",
    productImageSrc: productImageThree,
    productName: "Water Bottle",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageFour,
    productName: "USB Cable",
    productPrice: "৳15.00",
    productColor: "red",
  },
  {
    badge: true,
    badgeText: "new",
    productImageSrc: productImageOne,
    productName: "Wireless Earbuds",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageTwo,
    productName: "Bluetooth Headphones",
    productPrice: "৳15.00",
    productColor: "green",
  },
  {
    badge: false,
    badgeText: "10%",
    productImageSrc: productImageThree,
    productName: "Water Bottle",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageFour,
    productName: "USB Cable",
    productPrice: "৳15.00",
    productColor: "white",
  },
  {
    badge: true,
    badgeText: "new",
    productImageSrc: productImageOne,
    productName: "Wireless Earbuds",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageTwo,
    productName: "Bluetooth Headphones",
    productPrice: "৳15.00",
    productColor: "blue",
  },
  {
    badge: false,
    badgeText: "10%",
    productImageSrc: productImageThree,
    productName: "Water Bottle",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageFour,
    productName: "USB Cable",
    productPrice: "৳15.00",
    productColor: "red",
  },
  {
    badge: true,
    badgeText: "new",
    productImageSrc: productImageOne,
    productName: "Wireless Earbuds",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageTwo,
    productName: "Bluetooth Headphones",
    productPrice: "৳15.00",
    productColor: "green",
  },
  {
    badge: false,
    badgeText: "10%",
    productImageSrc: productImageThree,
    productName: "Water Bottle",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageFour,
    productName: "USB Cable",
    productPrice: "৳15.00",
    productColor: "white",
  },
  {
    badge: true,
    badgeText: "new",
    productImageSrc: productImageOne,
    productName: "Wireless Earbuds",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageTwo,
    productName: "Bluetooth Headphones",
    productPrice: "৳15.00",
    productColor: "blue",
  },
  {
    badge: false,
    badgeText: "10%",
    productImageSrc: productImageThree,
    productName: "Water Bottle",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageFour,
    productName: "USB Cable",
    productPrice: "৳15.00",
    productColor: "red",
  },
  {
    badge: true,
    badgeText: "new",
    productImageSrc: productImageOne,
    productName: "Wireless Earbuds",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageTwo,
    productName: "Bluetooth Headphones",
    productPrice: "৳15.00",
    productColor: "green",
  },
  {
    badge: false,
    badgeText: "10%",
    productImageSrc: productImageThree,
    productName: "Water Bottle",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageFour,
    productName: "USB Cable",
    productPrice: "৳15.00",
    productColor: "white",
  },
  {
    badge: true,
    badgeText: "new",
    productImageSrc: productImageOne,
    productName: "Wireless Earbuds",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageTwo,
    productName: "Bluetooth Headphones",
    productPrice: "৳15.00",
    productColor: "blue",
  },
  {
    badge: false,
    badgeText: "10%",
    productImageSrc: productImageThree,
    productName: "Water Bottle",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageFour,
    productName: "USB Cable",
    productPrice: "৳15.00",
    productColor: "red",
  },
  {
    badge: true,
    badgeText: "new",
    productImageSrc: productImageOne,
    productName: "Wireless Earbuds",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageTwo,
    productName: "Bluetooth Headphones",
    productPrice: "৳15.00",
    productColor: "green",
  },
  {
    badge: false,
    badgeText: "10%",
    productImageSrc: productImageThree,
    productName: "Water Bottle",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageFour,
    productName: "USB Cable",
    productPrice: "৳15.00",
    productColor: "white",
  },
  {
    badge: true,
    badgeText: "new",
    productImageSrc: productImageOne,
    productName: "Wireless Earbuds",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageTwo,
    productName: "Bluetooth Headphones",
    productPrice: "৳15.00",
    productColor: "blue",
  },
  {
    badge: false,
    badgeText: "10%",
    productImageSrc: productImageThree,
    productName: "Water Bottle",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badge: true,
    badgeText: "10%",
    productImageSrc: productImageFour,
    productName: "USB Cable",
    productPrice: "৳15.00",
    productColor: "red",
  },
];

let newarrivals = [
  {
    productImageSrc: productImageOne,
    productName: "Wireless Earbuds",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badgeText: "new",
    productImageSrc: productImageTwo,
    productName: "Bluetooth Headphones",
    productPrice: "৳15.00",
    productColor: "green",
  },
  {
    badgeText: "10%",
    productImageSrc: productImageThree,
    productName: "Water Bottle",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badgeText: "10%",
    productImageSrc: productImageFour,
    productName: "USB Cable",
    productPrice: "৳15.00",
    productColor: "white",
  },
  {
    badgeText: "new",
    productImageSrc: productImageOne,
    productName: "Wireless Earbuds",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    productImageSrc: productImageTwo,
    productName: "Bluetooth Headphones",
    productPrice: "৳15.00",
    productColor: "blue",
  },
  {
    badgeText: "10%",
    productImageSrc: productImageThree,
    productName: "Water Bottle",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badgeText: "10%",
    productImageSrc: productImageFour,
    productName: "USB Cable",
    productPrice: "৳15.00",
    productColor: "red",
  },
];

let bestsaller = [
  {
    
    productImageSrc: productImageFour,
    productName: "USB Cable",
    productPrice: "৳15.00",
    productColor: "white",
  },
  {
    badgeText: "new",
    productImageSrc: productImageOne,
    productName: "Wireless Earbuds",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badgeText: "10%",
    productImageSrc: productImageThree,
    productName: "Water Bottle",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    badgeText: "10%",
    productImageSrc: productImageTwo,
    productName: "Bluetooth Headphones",
    productPrice: "৳15.00",
    productColor: "green",
  },
];

let specialoffer = [
  {
   
    badgeText: "new",
    productImageSrc: productImageOne,
    productName: "Wireless Earbuds",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
    
    badgeText: "10%",
    productImageSrc: productImageTwo,
    productName: "Bluetooth Headphones",
    productPrice: "৳15.00",
    productColor: "green",
  },
  {
    
    productImageSrc: productImageThree,
    productName: "Water Bottle",
    productPrice: "৳15.00",
    productColor: "purple",
  },
  {
   
    badgeText: "10%",
    productImageSrc: productImageFour,
    productName: "USB Cable",
    productPrice: "৳15.00",
    productColor: "white",
  },
];

let category = [
  {
    name: "Women's Fashion",
    subcategory: [
      {
        name: "Dresses",
      },
      {
        name: "Tops & Blouses",
      },
      {
        name: "Bottoms & Jeans",
      },
    ],
  },
  {
    name: "Home & Living",
    subcategory: [
      {
        name: "Furniture",
      },
      {
        name: "Kitchenware",
      },
      {
        name: "Décors",
      },
    ],
  },
  {
    name: "Books & Stationery",
    subcategory: [
      {
        name: "Fiction",
      },
      {
        name: "Non-Fiction",
      },
      {
        name: "School & Office Supplie",
      },
    ],
  },
  {
    name: "Sports & Outdoor",
    subcategory: [
      {
        name: "Apparel & Footwear",
      },
      {
        name: "Equipment",
      },
      {
        name: "Activities",
      },
    ],
  },
  {
    name: "Toys & Games",
    subcategory: [
      {
        name: "Action Figures & Dolls",
      },
      {
        name: "Educational Toys",
      },
      {
        name: "Board Games & Puzzles",
      },
    ],
  },
  {
    name: "Food & Beverages",
    subcategory: [
      {
        name: "Snacks & Drinks",
      },
      {
        name: "Pantry Staples",
      },
      {
        name: "Fresh Produce",
      },
    ],
  },
];

let color = [
  {
    colorcode: "bg-teal-900",
    colorname: "Tell",
  },
  {
    colorcode: "bg-black",
    colorname: "Black",
  },
  {
    colorcode: "bg-gray-500",
    colorname: "Light gray",
  },
  {
    colorcode: "bg-yellow-200",
    colorname: "Yellow",
  },
  {
    colorcode: "bg-green-500",
    colorname: "Green",
  },
  {
    colorcode: "bg-red-500",
    colorname: "Red",
  },
];

let brand = [
  {
    name: "gucci",
  },
  {
    name: "apple",
  },
  {
    name: "samsung",
  },
  {
    name: "amazon",
  },
  {
    name: "h&m",
  },
  {
    name: "mts",
  },
];

let price = [
  {
    name: "৳0.00 - ৳9.99",
  },
  {
    name: "৳10.00 - ৳19.99",
  },
  {
    name: "৳20.00 - ৳29.99",
  },
  {
    name: "৳30.00 - ৳39.99",
  },
  {
    name: "৳40.00 - ৳49.99",
  },
  {
    name: "৳50.00+",
  },
];

export {
  productInfo,
  newarrivals,
  bestsaller,
  specialoffer,
  category,
  color,
  brand,
  price,
};
